{{- if .Values.namespace.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    {{- include "banking-demo.labels" . | nindent 4 }}
    phase: "8"
{{- end }}
